# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mariadb
import sys

class Ui_LoginWindow(object):

    def Login(self):
        svr = self.LeServer.text()
        uname = self.LeUname.text()
        passwd = self.LePasswd.text()
        
        try:
            connection = mariadb.connect(
            host= svr,
            user='root',
            passwd='redhat',
            port= 3306,
            database='lpr',
        )
        except mariadb.Error as e:
            self.LeMessage.setText("")
            self.LeMessage.setText("Connection to the server failed")
        else:
            self.LeMessage.setText("Connected to server..")
            
            cursor = connection.cursor()
            query = f"SELECT * FROM Users WHERE uname='{uname}' AND passwd='{passwd}'"
            cursor.execute(query)
            if not cursor.fetchone():
                self.LeMessage.setText("")
                self.LeMessage.setText("User name or password invalid")
            else:
                self.LeMessage.setText("User found")

    def Cancel(self):
        sys.exit()

    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.setWindowModality(QtCore.Qt.NonModal)
        LoginWindow.resize(344, 406)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LblServer = QtWidgets.QLabel(self.centralwidget)
        self.LblServer.setGeometry(QtCore.QRect(70, 100, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblServer.setFont(font)
        self.LblServer.setObjectName("LblServer")
        self.LblUname = QtWidgets.QLabel(self.centralwidget)
        self.LblUname.setGeometry(QtCore.QRect(70, 160, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblUname.setFont(font)
        self.LblUname.setObjectName("LblUname")
        self.LblPasswd = QtWidgets.QLabel(self.centralwidget)
        self.LblPasswd.setGeometry(QtCore.QRect(70, 220, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblPasswd.setFont(font)
        self.LblPasswd.setObjectName("LblPasswd")

        self.LeServer = QtWidgets.QLineEdit(self.centralwidget)
        self.LeServer.setGeometry(QtCore.QRect(70, 130, 191, 20))
        self.LeServer.setObjectName("LeServer")

        self.LeUname = QtWidgets.QLineEdit(self.centralwidget)
        self.LeUname.setGeometry(QtCore.QRect(70, 190, 191, 20))
        self.LeUname.setObjectName("LeUname")

        self.LePasswd = QtWidgets.QLineEdit(self.centralwidget)
        self.LePasswd.setGeometry(QtCore.QRect(70, 250, 191, 20))
        self.LePasswd.setObjectName("LePasswd")

        self.PbCancel = QtWidgets.QPushButton(self.centralwidget)
        self.PbCancel.setGeometry(QtCore.QRect(170, 300, 75, 23))
        self.PbCancel.setObjectName("PbCancel")
        self.PbCancel.clicked.connect(self.Cancel)
        
        self.PbConnect = QtWidgets.QPushButton(self.centralwidget)
        self.PbConnect.setGeometry(QtCore.QRect(90, 300, 75, 23))
        self.PbConnect.setObjectName("PbConnect")
        self.PbConnect.clicked.connect(self.Login)
        
        self.LeMessage = QtWidgets.QLabel(self.centralwidget)
        self.LeMessage.setGeometry(QtCore.QRect(30, 340, 281, 21))

        font = QtGui.QFont()
        font.setPointSize(10)
        self.LeMessage.setFont(font)
        self.LeMessage.setText("")
        self.LeMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.LeMessage.setObjectName("LeMessage")



        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 344, 21))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.LblServer.setText(_translate("LoginWindow", "Server:"))
        self.LblUname.setText(_translate("LoginWindow", "User name:"))
        self.LblPasswd.setText(_translate("LoginWindow", "Password:"))
        self.PbCancel.setText(_translate("LoginWindow", "Cancel"))
        self.PbConnect.setText(_translate("LoginWindow", "Connect"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
